TRUNCATE TABLE PROFESION;
TRUNCATE TABLE EMPLEADO;
TRUNCATE TABLE PACIENTE;
TRUNCATE TABLE EVALUACION;
TRUNCATE TABLE SINTOMA;
TRUNCATE TABLE DETALLE_EVALUACION;
TRUNCATE TABLE DIAGNOSTICO;
TRUNCATE TABLE SINTOMA_DIAGNOSTICO;
TRUNCATE TABLE TRATAMIENTO;
TRUNCATE TABLE DETALLE_TRATAMIENTO;

--Insertamos los Datos de Nuestra Tabla Temporal hacia Nuestro Modelo E-R

--Insertamos Las Profesiones
INSERT INTO Profesion (Nombre) 
SELECT DISTINCT TITULO_DEL_EMPLEADO FROM Temporal WHERE TITULO_DEL_EMPLEADO IS NOT NULL ;

--Insertamos Los Empleados del Centro 
SELECT DISTINCT
t.NOMBRE_EMPLEADO, t.APELLIDO_EMPLEADO, t.DIRECCION_EMPLEADO, t.TELEFONO_EMPLEADO,
t.GENERO_EMPLEADO, t.FECHA_NACIMIENTO_EMPLEADO, t.TITULO_DEL_EMPLEADO
FROM Temporal t;