TRUNCATE TABLE PROFESION;
TRUNCATE TABLE EMPLEADO;
TRUNCATE TABLE PACIENTE;
TRUNCATE TABLE EVALUACION;
TRUNCATE TABLE SINTOMA;
TRUNCATE TABLE DETALLE_EVALUACION;
TRUNCATE TABLE DIAGNOSTICO;
TRUNCATE TABLE SINTOMA_DIAGNOSTICO;
TRUNCATE TABLE TRATAMIENTO;
TRUNCATE TABLE DETALLE_TRATAMIENTO;

--Insertamos los Datos de Nuestra Tabla Temporal hacia Nuestro Modelo E-R

--Insertamos Las Profesiones