TRUNCATE TABLE PROFESION;
TRUNCATE TABLE EMPLEADO;
TRUNCATE TABLE PACIENTE;
TRUNCATE TABLE EVALUACION;
TRUNCATE TABLE SINTOMA;
TRUNCATE TABLE DETALLE_EVALUACION;
TRUNCATE TABLE DIAGNOSTICO;
TRUNCATE TABLE SINTOMA_DIAGNOSTICO;
TRUNCATE TABLE TRATAMIENTO;
TRUNCATE TABLE DETALLE_TRATAMIENTO;

--Insertamos los Datos de Nuestra Tabla Temporal hacia Nuestro Modelo E-R

--Insertamos Las Profesiones
INSERT INTO profesion (
    nombre
) 
SELECT DISTINCT 
    TITULO_DEL_EMPLEADO 
FROM temporal 
WHERE TITULO_DEL_EMPLEADO IS NOT NULL ;

--Insertamos Los Empleados del Centro 
INSERT INTO empleado (
    nombre,
    apellidos,
    direccion,
    telefono,
    fecha_nacimiento,
    genero,
    id_profesion
)
SELECT DISTINCT
    t.NOMBRE_EMPLEADO,
    t.APELLIDO_EMPLEADO, 
    t.DIRECCION_EMPLEADO, 
    t.TELEFONO_EMPLEADO,
    t.FECHA_NACIMIENTO_EMPLEADO, 
    t.GENERO_EMPLEADO, 
    (SELECT id_profesion FROM profesion WHERE nombre=t.TITULO_DEL_EMPLEADO)
FROM Temporal t
WHERE   t.NOMBRE_EMPLEADO IS NOT NULL AND 
        t.APELLIDO_EMPLEADO IS NOT NULL AND
        t.DIRECCION_EMPLEADO IS NOT NULL AND
        t.TELEFONO_EMPLEADO IS NOT NULL AND 
        t.GENERO_EMPLEADO IS NOT NULL AND 
        t.FECHA_NACIMIENTO_EMPLEADO IS NOT NULL AND
        t.TITULO_DEL_EMPLEADO  IS NOT NULL;