--Ejecuta La Carga hacia la tabla temporal creada en el IntruccionesDDL.sql
--sqlldr userid=system control='[BD1]ArchivoControl.ctl'

SELECT * FROM PROFESION;
SELECT * FROM EMPLEADO;

SELECT DISTINCT
t.NOMBRE_EMPLEADO, t.APELLIDO_EMPLEADO, t.DIRECCION_EMPLEADO, t.TELEFONO_EMPLEADO,
t.GENERO_EMPLEADO, t.FECHA_NACIMIENTO_EMPLEADO, t.TITULO_DEL_EMPLEADO
FROM Temporal t;

SELECT COUNT(*) FROM  (SELECT DISTINCT
t.NOMBRE_EMPLEADO, t.APELLIDO_EMPLEADO, t.DIRECCION_EMPLEADO, t.TELEFONO_EMPLEADO,
t.GENERO_EMPLEADO, t.FECHA_NACIMIENTO_EMPLEADO, t.TITULO_DEL_EMPLEADO
FROM Temporal t
WHERE hubiera  IS NOT NULL
);